version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./docker/backend/.dev.env
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    restart: unless-stopped
    depends_on:
      - pgadmin
    networks:
      - ralmet
  postgres:
    container_name: postgres
    image: postgres:16rc1-alpine3.18
    env_file:
      - ./docker/postgres/.dev.env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./docker/postgres/dump:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - ralmet
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - ralmet
    restart: unless-stopped
networks:
  ralmet:
    driver: bridge
